[package]
name = "basic"
version = "0.1.0"
authors = ["boxdot <d@zerovolt.org>", "jeschkies <k@jeschkies.xyz>"]
edition = "2018"

[dependencies]
itertools = "0.8.0"
nom = "5.0.0"
rand = "0.7.0"
rand_xorshift = "0.2.0"

[dev-dependencies]
diff = "0.1.11"

[workspace]
members = ["wasm"]
